server:
  port: 8888
  tomcat:
    accesslog:
      enabled: true
    threads:
      min-spare: 300
      max: 3000
    connection-timeout: 10000
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  application:
    name: javaCupDemo
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

service:
  baseUrl: /services/javaCupDemo
  swagger:
    version: 'version1.1.0-1404/02/05'
    title: 'javaCupDemo server'
    description: 'javaCupDemo server'

springdoc:
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    display-operation-id: true
    tags-sorter: alpha
  api-docs:
    path: ${service.baseUrl}/v3/api-docs
